### ISSUE TITLE
EISDIR: illegal operation on a directory for readFile method

### ISSUE THREAD

**Issue by ruhankhandakar** [itinance/react-native-fs#1002]
```
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:592:3)
    at tryReadSync (fs.js:366:20)
    at Object.readFileSync (fs.js:403:19)
    at UnableToResolveError.buildCodeFrameMessage (/Users/ruhan/Desktop/pickrr/pickrr-mobile-app/Pickrr/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:347:17)
    at new UnableToResolveError (/Users/ruhan/Desktop/pickrr/pickrr-mobile-app/Pickrr/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:333:35)
    at ModuleResolver.resolveDependency (/Users/ruhan/Desktop/pickrr/pickrr-mobile-app/Pickrr/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:211:15)
    at DependencyGraph.resolveDependency (/Users/ruhan/Desktop/pickrr/pickrr-mobile-app/Pickrr/node_modules/metro/src/node-haste/DependencyGraph.js:413:43)
    at /Users/ruhan/Desktop/pickrr/pickrr-mobile-app/Pickrr/node_modules/metro/src/lib/transformHelpers.js:317:42
    at /Users/ruhan/Desktop/pickrr/pickrr-mobile-app/Pickrr/node_modules/metro/src/Server.js:1471:14
    at Generator.next (<anonymous>)
```

Version -> "react-native-fs": "^2.17.0",   "react-native": "0.64.0",
Device -> Mac
Using React native CLI
Sample Code ->

  ```
const handlePress = async () => {
    try {
      const res = await DocumentPicker.pick({
        type: [DocumentPicker.types.allFiles],
      });
      if (res) {
        const filePath =
          Platform.OS === 'android' ? res.uri : res.uri.replace('file://', '');
        const file = await RNFS.readFile(filePath, 'base64');
        setFiles({
          file,
          type: res.type,
          size: res.size,
        });
      }
    } catch (err) {
      if (DocumentPicker.isCancel(err)) {
        // User cancelled the picker, exit any dialogs or menus and move on
      } else {
        Alert.alert(err.message);
      }
    }
  };
```

**Comment by disrae** [comment]
For me, an absolute path without 'file://' is working.
