### ISSUE TITLE
unexpected syntax error coming in react-native-fs 

### ISSUE THREAD

**Issue by dusklight00** [itinance/react-native-fs#1134]
**Error**
When importing `react-native-fs` in a react component, like this
```js
import RNFS from 'react-native-fs';
```
It automatically generates the following errors without doing anything else
```cmd
X [ERROR] Expected ")" but found ":"

    node_modules/react-native-fs/FS.common.js:30:29:
      30 │ var normalizeFilePath = (path: string) => (path.startsWith('file://') ? path.slice(7) : path);
         │                              ^
         ╵                              )

9:31:53 am [vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/react-native-fs/FS.common.js:30:29: ERROR: Expected ")" but found ":"
    at failureErrorWithLog (C:\Users\ASC\Documents\GitHub\board-scanner\view\node_modules\esbuild\lib\main.js:1566:15)
    at C:\Users\ASC\Documents\GitHub\board-scanner\view\node_modules\esbuild\lib\main.js:1024:28
    at runOnEndCallbacks (C:\Users\ASC\Documents\GitHub\board-scanner\view\node_modules\esbuild\lib\main.js:1438:61)
    at buildResponseToResult (C:\Users\ASC\Documents\GitHub\board-scanner\view\node_modules\esbuild\lib\main.js:1022:7)
    at C:\Users\ASC\Documents\GitHub\board-scanner\view\node_modules\esbuild\lib\main.js:1134:14
    at responseCallbacks.<computed> (C:\Users\ASC\Documents\GitHub\board-scanner\view\node_modules\esbuild\lib\main.js:671:9)
    at handleIncomingPacket (C:\Users\ASC\Documents\GitHub\board-scanner\view\node_modules\esbuild\lib\main.js:726:9)
    at Socket.readFromStdout (C:\Users\ASC\Documents\GitHub\board-scanner\view\node_modules\esbuild\lib\main.js:647:7)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)
```

**Steps to Reproduce**
- Import `react-native-fs` using the command `import RNFS from 'react-native-fs';` in your react component

**Images**
![image](https://user-images.githubusercontent.com/71203637/193732352-eabedd89-a512-47d5-ace9-6157bbc7dbe0.png)

**Comment by JishnuNaidu** [comment]
How did you solve the above problem

**Comment by SalahAdDin** [comment]
It seems no one fixed this yet.
