### ISSUE TITLE
JEST-test failed: Cannot read property 'RNFSFileTypeRegular' of undefined

### ISSUE THREAD

**Issue by vdlindenmark** [itinance/react-native-fs#404]
My app runs and work correctly on Android and iOS, but when i run a jest test (at this moment without a specific test for RNFS but with a test for some screens where RNFS is used) it fails with the following error.
```
Test suite failed to run

    TypeError: Cannot read property 'RNFSFileTypeRegular' of undefined
      
      at Object.<anonymous> (node_modules/react-native-fs/FS.common.js:18:37)
      at Object.<anonymous> (app/helpers/SaveDecodeImage.js:1:711)
      at Object.<anonymous> (app/helpers/API.js:9:22)
```

I don'n know how to fix this issue...

**Comment by vdlindenmark** [comment]
Fix for now is to mock everything. But i would like to test react-native-fs with jest, so then i can't mock it and have to use it. How can i do that?

**Comment by SoundBlaster** [comment]
@vdlindenmark can you please show you mock?

**Comment by vdlindenmark** [comment]
@SoundBlaster 
```
jest.mock('react-native-fs', () => {
  return {
    mkdir: jest.fn(),
    moveFile: jest.fn(),
    copyFile: jest.fn(),
    pathForBundle: jest.fn(),
    pathForGroup: jest.fn(),
    getFSInfo: jest.fn(),
    getAllExternalFilesDirs: jest.fn(),
    unlink: jest.fn(),
    exists: jest.fn(),
    stopDownload: jest.fn(),
    resumeDownload: jest.fn(),
    isResumable: jest.fn(),
    stopUpload: jest.fn(),
    completeHandlerIOS: jest.fn(),
    readDir: jest.fn(),
    readDirAssets: jest.fn(),
    existsAssets: jest.fn(),
    readdir: jest.fn(),
    setReadable: jest.fn(),
    stat: jest.fn(),
    readFile: jest.fn(),
    read: jest.fn(),
    readFileAssets: jest.fn(),
    hash: jest.fn(),
    copyFileAssets: jest.fn(),
    copyFileAssetsIOS: jest.fn(),
    copyAssetsVideoIOS: jest.fn(),
    writeFile: jest.fn(),
    appendFile: jest.fn(),
    write: jest.fn(),
    downloadFile: jest.fn(),
    uploadFiles: jest.fn(),
    touch: jest.fn(),
    MainBundlePath: jest.fn(),
    CachesDirectoryPath: jest.fn(),
    DocumentDirectoryPath: jest.fn(),
    ExternalDirectoryPath: jest.fn(),
    ExternalStorageDirectoryPath: jest.fn(),
    TemporaryDirectoryPath: jest.fn(),
    LibraryDirectoryPath: jest.fn(),
    PicturesDirectoryPath: jest.fn(),
  };
});
```

**Comment by AndrewHenderson** [comment]
@vdlindenmark That will allow your tests to run if your app files import `react-native-fs`. However, you'll find that none of your property mocks are present – it's just a basic jest mock object. Calling any of those property functions in your app files will break your tests, since they'll be undefined.

If you want to create those property mocks, you'll need to define them after the mock has been initialized. See: https://jestjs.io/docs/en/manual-mocks#examples.

```js
// /__mocks__/react-native-fs.js
const RNFS = jest.mock('react-native-fs');

RNFS.moveFile = jest.fn();
RNFS.copyFile = jest.fn();
RNFS.unlink = jest.fn();
…

export default RNFS;
```

**Comment by angelos3lex** [comment]
@vdlindenmark Where should i place this code? If i place it inside my test(...) before expect(..) or generally anywhere in my test.js file, the error persists.

**Comment by vdlindenmark** [comment]
In your jest config

**Comment by rpuls** [comment]
> If you place the mock in the `node_modules` mocks directory, you'll have to use a different syntax.
> 
> ```js
> // /__mocks__/react-native-fs.js
> export default {
>   mkdir: jest.fn(),
>   moveFile: jest.fn(),
>   copyFile: jest.fn(),
>   …
> };
> ```

I would recommend doing:

module.export = {
  mkdir: jest.fn(),
  ...
}

Instead, as that is how the functinos are exported in FS.common.js
But then u should be good.

**Comment by kg-currenxie** [comment]
Still no solution without mocking? We load translation files via rn-fs, with mocking the app won't show any text at all, and can't test changing locale.

**Comment by prasannavenkatesh-colan** [comment]
> @SoundBlaster
> 
> ```
> jest.mock('react-native-fs', () => {
>   return {
>     mkdir: jest.fn(),
>     moveFile: jest.fn(),
>     copyFile: jest.fn(),
>     pathForBundle: jest.fn(),
>     ...
>   };
> });
> ```

Working  for me

**Comment by arthwood** [comment]
Apparently no need to mock everything. In `__mocks__/react-native-fs.js` I only have:
```
export default {}
```
and test are passing now. (even exporting `undefined` would do)

**Comment by swordensen** [comment]
> Apparently no need to mock everything. In `__mocks__/react-native-fs.js` I only have:
> 
> ```
> export default {}
> ```
> 
> and test are passing now. (even exporting `undefined` would do)

this worked for me as well and I used the mock functions to make my specific tests work and potentially implement a node-fs mock

```js
export default {
    mkdir: jest.fn(),
    moveFile: jest.fn(),
    copyFile: jest.fn(),
    pathForBundle: jest.fn(),
    pathForGroup: jest.fn(),
    getFSInfo: jest.fn(),
    getAllExternalFilesDirs: jest.fn(),
    unlink: jest.fn(),
    exists: jest.fn(),
    stopDownload: jest.fn(),
    resumeDownload: jest.fn(),
    isResumable: jest.fn(),
    stopUpload: jest.fn(),
    completeHandlerIOS: jest.fn(),
    readDir: jest.fn(),
    readDirAssets: jest.fn(),
    existsAssets: jest.fn(),
    readdir: jest.fn(),
    setReadable: jest.fn(),
    stat: jest.fn(),
    readFile: jest.fn(),
    read: jest.fn(),
    readFileAssets: jest.fn(),
    hash: jest.fn(),
    copyFileAssets: jest.fn(),
    copyFileAssetsIOS: jest.fn(),
    copyAssetsVideoIOS: jest.fn(),
    writeFile: jest.fn(),
    appendFile: jest.fn(),
    write: jest.fn(),
    downloadFile: jest.fn(),
    uploadFiles: jest.fn(),
    touch: jest.fn(),
    MainBundlePath: jest.fn(),
    CachesDirectoryPath: jest.fn(),
    DocumentDirectoryPath: jest.fn(),
    ExternalDirectoryPath: jest.fn(),
    ExternalStorageDirectoryPath: jest.fn(),
    TemporaryDirectoryPath: jest.fn(),
    LibraryDirectoryPath: jest.fn(),
    PicturesDirectoryPath: jest.fn(),
}

export const mkdir =  jest.fn()
export const moveFile =  jest.fn()
export const copyFile =  jest.fn()
export const pathForBundle =  jest.fn()
export const pathForGroup =  jest.fn()
export const getFSInfo =  jest.fn()
export const getAllExternalFilesDirs =  jest.fn()
export const unlink =  jest.fn()
export const exists =  jest.fn()
export const stopDownload =  jest.fn()
export const resumeDownload =  jest.fn()
export const isResumable =  jest.fn()
export const stopUpload =  jest.fn()
export const completeHandlerIOS =  jest.fn()
export const readDir =  jest.fn()
export const readDirAssets =  jest.fn()
export const existsAssets =  jest.fn()
export const readdir =  jest.fn()
export const setReadable =  jest.fn()
export const stat =  jest.fn()
export const readFile =  jest.fn()
export const read =  jest.fn()
export const readFileAssets =  jest.fn()
export const hash =  jest.fn()
export const copyFileAssets =  jest.fn()
export const copyFileAssetsIOS =  jest.fn()
export const copyAssetsVideoIOS =  jest.fn()
export const writeFile =  jest.fn()
export const appendFile =  jest.fn()
export const write =  jest.fn()
export const downloadFile =  jest.fn()
export const uploadFiles =  jest.fn()
export const touch =  jest.fn()
export const MainBundlePath =  jest.fn()
export const CachesDirectoryPath =  jest.fn()
export const DocumentDirectoryPath =  jest.fn()
export const ExternalDirectoryPath =  jest.fn()
export const ExternalStorageDirectoryPath =  jest.fn()
export const TemporaryDirectoryPath =  jest.fn()
export const LibraryDirectoryPath =  jest.fn()
export const PicturesDirectoryPath =  jest.fn()
```
