### ISSUE TITLE
react-native link react-native-fs errors

### ISSUE THREAD

**Issue by markentingh** [itinance/react-native-fs#508]
When trying to link the library, I get the following error

```
Expected "/* Begin ", "/* End ", "\"", or [A-Za-z0-9_.] but "<" found.
```

**Comment by ScreamZ** [comment]
Windows and react native are painful… try search on the internet windows and react native related issues.

**Comment by QQ10388577** [comment]
你好！请问你那边有React Native ios APP上架的技术或者有认识的朋友可以合作吗？打扰见谅！

**Comment by giantss** [comment]
same here.
### My environment

```
{
  "name": "MapboxTest",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "@mapbox/react-native-mapbox-gl": "^6.1.3",
    "react": "16.6.1",
    "react-native": "0.57.5",
    "react-native-fs": "^2.12.1"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.49.2",
    "react-test-renderer": "16.6.1"
  },
  "jest": {
    "preset": "react-native"
  }
}

```
After executing `react-native link react-native-fs`, the following error message appears: 


```
giants-2:MapboxTest zhongpeng$ react-native link react-native-fs
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'asap/raw'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/zhongpeng/file/code/react-native/test/MapboxTest/node_modules/promise/lib/core.js:3:12)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._compile (/Users/zhongpeng/file/code/react-native/test/MapboxTest/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.newLoader [as .js] (/Users/zhongpeng/file/code/react-native/test/MapboxTest/node_modules/pirates/lib/index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
giants-2:MapboxTest zhongpeng$ react-native link react-native-fs
internal/modules/cjs/loader.js:583

```
