### ISSUE TITLE
RNFS.uploadFiles [Error: unexpected end of stream] framesToPop: 1, code: 'EUNSPECIFIED'

### ISSUE THREAD

**Issue by cafeasia3** [itinance/react-native-fs#596]
I tried it on android emulator, I am using the sample upload code and it return 
`[Error: unexpected end of stream] framesToPop: 1, code: 'EUNSPECIFIED'`

This is the code I am using

```
async uploadImageReq(){
    var url = this.API_BASE_URL + '/api/addimages/'
    var uploadBegin = (response) => {
      var jobId = response.jobId;
      console.log('UPLOAD HAS BEGUN! JobId: ' + jobId);
    };

    var uploadProgress = (response) => {
      var percentage = Math.floor((response.totalBytesSent/response.totalBytesExpectedToSend) * 100);
      console.log('UPLOAD IS ' + percentage + '% DONE!');
    };
    console.log('check url', url, files) 
    return await RNFS.uploadFiles({
      toUrl: url,
      files: files,
      method: 'POST',
      headers: {
        'Accept': 'application/json',
        'Authorization': 'Bearer ' + this._sessionToken,
        'Connection': 'close'
      },
      fields: {
        'hello': 'world',
      },
      begin: uploadBegin,
      progress: uploadProgress
    }).promise.then((response) => {
        console.log('result', response)
        return response
        if (response.statusCode == 200) {
          console.log('FILES UPLOADED!'); // response.statusCode, response.headers, response.body
        } else {
          console.log('SERVER ERROR');
        }
      })
      .catch((err) => {
        if(err.description === "cancelled") {
          // cancelled by user
        }
        console.log('ERROR',err);
      })
  }

```

Should be same code as sample code on the documentation. it stop at 
console.log('UPLOAD HAS BEGUN! JobId: ' + jobId);

then error 

> [Error: unexpected end of stream] framesToPop: 1, code: 'EUNSPECIFIED'

Any idea What cause this error?

**Comment by sinodko** [comment]
@cafeasia3 did you solve your issue?

**Comment by RichardLindhout** [comment]
```

java.net.MalformedURLException: no protocol: /calamity/pdf/38
2019-02-28 17:03:11.851 7269-10472/com.eyeontarget W/System.err:     at java.net.URL.<init>(URL.java:601)
2019-02-28 17:03:11.851 7269-10472/com.eyeontarget W/System.err:     at java.net.URL.<init>(URL.java:498)
2019-02-28 17:03:11.851 7269-10472/com.eyeontarget W/System.err:     at java.net.URL.<init>(URL.java:447)
2019-02-28 17:03:11.851 7269-10472/com.eyeontarget W/System.err:     at com.rnfs.RNFSManager.downloadFile(RNFSManager.java:634)
2019-02-28 17:03:11.851 7269-10472/com.eyeontarget W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2019-02-28 17:03:11.851 7269-10472/com.eyeontarget W/System.err:     at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
2019-02-28 17:03:11.851 7269-10472/com.eyeontarget W/System.err:     at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
2019-02-28 17:03:11.851 7269-10472/com.eyeontarget W/System.err:     at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
2019-02-28 17:03:11.851 7269-10472/com.eyeontarget W/System.err:     at android.os.Handler.handleCallback(Handler.java:873)
2019-02-28 17:03:11.851 7269-10472/com.eyeontarget W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2019-02-28 17:03:11.851 7269-10472/com.eyeontarget W/System.err:     at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
2019-02-28 17:03:11.851 7269-10472/com.eyeontarget W/System.err:     at android.os.Looper.loop(Looper.java:193)
2019-02-28 17:03:11.851 7269-10472/com.eyeontarget W/System.err:     at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
2019-02-28 17:03:11.851 7269-10472/com.eyeontarget W/System.err:     at java.lang.Thread.run(Thread.java:764)
2019-02-28 17:03:11.855 7269-10471/com.eyeontarget I/ReactNativeJS: { [Error: no protocol: /calamity/pdf/38]
      framesToPop: 1,
      nativeStackAndroid: [],
      userInfo: null,
      code: 'EUNSPECIFIED' }
```

**Comment by RichardLindhout** [comment]
My url was wrong ;)

**Comment by kwm168** [comment]
> I tried it on android emulator, I am using the sample upload code and it return
> `[Error: unexpected end of stream] framesToPop: 1, code: 'EUNSPECIFIED'`
> 
> This is the code I am using
> 
> ```
> async uploadImageReq(){
>     var url = this.API_BASE_URL + '/api/addimages/'
>     var uploadBegin = (response) => {
>       var jobId = response.jobId;
>       console.log('UPLOAD HAS BEGUN! JobId: ' + jobId);
>     };
> 
>     var uploadProgress = (response) => {
>       var percentage = Math.floor((response.totalBytesSent/response.totalBytesExpectedToSend) * 100);
>       console.log('UPLOAD IS ' + percentage + '% DONE!');
>     };
>     console.log('check url', url, files) 
>     return await RNFS.uploadFiles({
>       toUrl: url,
>       files: files,
>       method: 'POST',
>       headers: {
>         'Accept': 'application/json',
>         'Authorization': 'Bearer ' + this._sessionToken,
>         'Connection': 'close'
>       },
>       fields: {
>         'hello': 'world',
>       },
>       begin: uploadBegin,
>       progress: uploadProgress
>     }).promise.then((response) => {
>         console.log('result', response)
>         return response
>         if (response.statusCode == 200) {
>           console.log('FILES UPLOADED!'); // response.statusCode, response.headers, response.body
>         } else {
>           console.log('SERVER ERROR');
>         }
>       })
>       .catch((err) => {
>         if(err.description === "cancelled") {
>           // cancelled by user
>         }
>         console.log('ERROR',err);
>       })
>   }
> ```
> Should be same code as sample code on the documentation. it stop at
> console.log('UPLOAD HAS BEGUN! JobId: ' + jobId);
> 
> then error
> 
> > [Error: unexpected end of stream] framesToPop: 1, code: 'EUNSPECIFIED'
> 
> Any idea What cause this error?

I followed the same exact way as you did but my error is this

[Error: Socket closed]

Any idea?

**Comment by aliazizi** [comment]
sampe problem

**Comment by hank121314** [comment]
@aliazizi Can you provide a log as RichardLindhout have provided? So I can get into this bug.

**Comment by aliazizi** [comment]
I found your example in main repo readme is not working for android
Because I access to content://  directly. So I sent to fetch api `{ uri: res.uri, type: res.type, name: encodeURI(res.fileName) }` like this and my problem solved.

You should update readme section for android

**Comment by aliazizi** [comment]
I use `react-native-document-picker` wich provide `content://` uri for file, And use it's example to upload file with this library.
I figure out the problem is from example code, also this library can't use `content://` uri 
so i changed my code and use fetch api for uploading and everything is working now

**Comment by MuhammetAdamoglu** [comment]
@aliazizi hey, can you send example code.

**Comment by aliazizi** [comment]
@samueljmurray  Im sorry I make a mistake, It's example of https://github.com/Elyx0/react-native-document-picker in readme, I send wrong post here

**Comment by sandeepsinghs** [comment]
I am also getting the same error. I am not getting the real Path of file. 

Please help someone.

**Comment by NooruddinLakhani** [comment]
I'm getting the same error {framesToPop: 1, code: 'EUNSPECIFIED'}

I have the following code

```
RNFS.uploadFiles({
      toUrl: uploadUrl,
      files,
      method: "POST",
      headers: {
        Accept: "application/json",
        // "Transfer-Encoding": "Chunked",
        // "Content-Type": "multipart/form-data",
        "X-Access-Token": accessToken,
      },
      fields: {},
      begin: uploadBegin,
      connectionTimeout: 1500,
      readTimeout: 1500,
      progress: uploadProgress,
    })
      .promise.then(response => {
        if (response.statusCode == 200) {
          console.log("FILES UPLOADED!:"); // response.statusCode, response.headers, response.body
          onSuccess(JSON.parse(response.body));
        } else {
          console.log("SERVER ERROR");
          failureCallback(`Server Error: ${response.body.stringify()}`);
        }
      })
      .catch(err => {
        if (err.description === "cancelled") {
          // cancelled by user
        }
        console.log(`RNBlob.uploadFile error: ${err.messsage}`);
        failureCallback(err);
      });
```

File-path is "/data/user/0/com.givaoke.app/cache/audioVideoFinal.mp4"

What to do now?

**Comment by rajesh-rt** [comment]
Any update in this?
Its working fine on iOS but getting this issue on Android.
Any help is much appreciated.

**Comment by vladimirevstratov** [comment]
Same issue

**Comment by ol4juwon** [comment]
Any help with this?

**Comment by crackhack8266** [comment]
still facing the issue anyone have any idea please share

**Comment by woowalker** [comment]
crazy same
