### ISSUE TITLE
uploadFiles Api is not working is throws "ENOENT: no such file or directory, open <uplaod url>"

### ISSUE THREAD

**Issue by Anu1612** [itinance/react-native-fs#799]
Hi,
I need to upload a excel file to the server from android file system.

The file is In document directory i know as when RNFS.exists() is called with the file path is returns true. But as is upload the files using UplaodFiles api the progress went to 99% and then failed giving error "ENOENT: no such file or directory, open <uplaod url>"

**Comment by tahajahangir** [comment]
No plan to fix this?

**Comment by tahajahangir** [comment]
The underlying Java exception is:

```
java.io.FileNotFoundException: <URL HERE>                                         
   at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:251)                      
   at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)        
   at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(Unknown Source:0)                                   
   at com.rnfs.Uploader.upload(Uploader.java:169)                                                                               
   at com.rnfs.Uploader.access$200(Uploader.java:23)                                                                            
   at com.rnfs.Uploader$1.run(Uploader.java:36)                                                                                 
   at java.lang.Thread.run(Thread.java:764)
```

**Comment by Thram** [comment]
This started to happen for no reason all of the sudden.
It was working fine and suddenly started to show this error... Any clue of what is this about?

**Comment by Thram** [comment]
I found my problem was in the server.
The server was throwing an error but I don't know for what reason `react-native-fs` was showing this nonsense error instead.
It seems this is not a bug in terms of functionality, but would be nice to have a better error handling.
Thanks

**Comment by denichodev** [comment]
Hi @Thram and @tahajahangir, I've opened a PR to fix this https://github.com/itinance/react-native-fs/pull/944, you can use that to patch your package to handle error better.
