### ISSUE TITLE
Could not invoke RNFSManager.readFile

### ISSUE THREAD

**Issue by shengliZh** [itinance/react-native-fs#891]
2020-06-04 15:23:36.785 5046-5071/? E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.sirenrn, PID: 5046
    java.lang.RuntimeException: Could not invoke RNFSManager.readFile
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:383)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:164)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158) 
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
        at android.os.Handler.handleCallback(Handler.java:789) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29) 
        at android.os.Looper.loop(Looper.java:164) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: java.lang.OutOfMemoryError: Failed to allocate a 120113568 byte allocation with 25165824 free bytes and 79MB until OOM, max allowed footprint 479151928, growth limit 536870912
        at java.lang.StringFactory.newStringFromChars(StringFactory.java:220)
        at java.lang.StringFactory.newStringFromBytes(StringFactory.java:205)
        at java.lang.StringFactory.newStringFromBytes(StringFactory.java:65)
        at android.util.Base64.encodeToString(Base64.java:456)
        at com.rnfs.RNFSManager.readFile(RNFSManager.java:219)
        at java.lang.reflect.Method.invoke(Native Method)

**Comment by RahulkrishnanSpericorn** [comment]
Same issue

**Comment by react06** [comment]
same here!
